### ISSUE TITLE
type mismatch trying to load plugin

### ISSUE THREAD

**Issue by bkindley** [sbt/sbt-testng#12]
sbt 0.13.11

```
 error: type mismatch;
 found   : de.johoop.testngplugin.TestNGPlugin.type
 required: sbt.Plugins
  enablePlugins(de.johoop.testngplugin.TestNGPlugin).

[debug] [naha] 
[debug] [naha] Initial source changes: 
[debug] [naha]  removed:Set()
[debug] [naha]  added: Set()
[debug] [naha]  modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set()
[debug] [naha] 
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha]  product: Set()
[debug] [naha]  binary dep: Set()
[debug] [naha]  external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]  
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Forcing garbage collection...
[debug] [Loading] Scanning directory /home/stuff
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /home/stuff/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)
[debug] sorting: ns: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin) not found List(sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin) not found List(sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin) not found List(sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin) not found List()
[debug]   :: sorted deduced result: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug] [Loading] Done in /home/bkindley/stuff/project, returning: (scala-build)
[info] Loading project definition from /home/stuff/project
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
[debug] [naha] 
[debug] [naha] Initial source changes: 
[debug] [naha]  removed:Set()
[debug] [naha]  added: Set()
[debug] [naha]  modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set()
[debug] [naha] 
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha]  product: Set()
[debug] [naha]  binary dep: Set()
[debug] [naha]  external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug]  
[debug] [Loading] Scanning directory /home/stuff
[debug] Type error in expression
[debug]     at sbt.compiler.Eval.checkError(Eval.scala:384)
[debug]     at sbt.compiler.Eval.compileAndLoad(Eval.scala:183)
[debug]     at sbt.compiler.Eval.evalCommon(Eval.scala:152)
[debug]     at sbt.compiler.Eval.evalDefinitions(Eval.scala:122)
[debug]     at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:271)
[debug]     at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:109)
[debug]     at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:725)
[debug]     at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:731)
[debug]     at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:730)
[debug]     at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
[debug]     at scala.collection.AbstractMap.getOrElse(Map.scala:58)
[debug]     at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:730)
[debug]     at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:738)
[debug]     at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:738)
[debug]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[debug]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[debug]     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[debug]     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[debug]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[debug]     at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[debug]     at sbt.Load$.loadFiles$1(Load.scala:738)
[debug]     at sbt.Load$.discoverProjects(Load.scala:749)
[debug]     at sbt.Load$.discover$1(Load.scala:555)
[debug]     at sbt.Load$.loadTransitive(Load.scala:584)
[debug]     at sbt.Load$.loadProjects$1(Load.scala:452)
[debug]     at sbt.Load$.loadUnit(Load.scala:456)
[debug]     at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
[debug]     at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
[debug]     at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
[debug]     at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
[debug]     at sbt.BuildLoader.apply(BuildLoader.scala:140)
[debug]     at sbt.Load$.loadAll(Load.scala:344)
[debug]     at sbt.Load$.loadURI(Load.scala:299)
[debug]     at sbt.Load$.load(Load.scala:295)
[debug]     at sbt.Load$.load(Load.scala:286)
[debug]     at sbt.Load$.apply(Load.scala:140)
[debug]     at sbt.Load$.defaultLoad(Load.scala:36)
[debug]     at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
[debug]     at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
[debug]     at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
[debug]     at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
[debug]     at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
[debug]     at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
[debug]     at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
[debug]     at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
[debug]     at sbt.Command$.process(Command.scala:93)
[debug]     at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
[debug]     at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
[debug]     at sbt.State$$anon$1.process(State.scala:184)
[debug]     at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
[debug]     at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
[debug]     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[debug]     at sbt.MainLoop$.next(MainLoop.scala:96)
[debug]     at sbt.MainLoop$.run(MainLoop.scala:89)
[debug]     at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
[debug]     at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
[debug]     at sbt.Using.apply(Using.scala:24)
[debug]     at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
[debug]     at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
[debug]     at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
[debug]     at sbt.MainLoop$.runLogged(MainLoop.scala:22)
[debug]     at sbt.StandardMain$.runManaged(Main.scala:54)
[debug]     at sbt.xMain.run(Main.scala:29)
[debug]     at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[debug]     at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[debug]     at xsbt.boot.Launch$.run(Launch.scala:109)
[debug]     at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[debug]     at xsbt.boot.Launch$.launch(Launch.scala:117)
[debug]     at xsbt.boot.Launch$.apply(Launch.scala:18)
[debug]     at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[debug]     at xsbt.boot.Boot$.main(Boot.scala:17)
[debug]     at xsbt.boot.Boot.main(Boot.scala)
sbt.compiler.EvalException: Type error in expression
```

**Comment by xuwei-k** [comment]
You can't use `enablePlugins` because this is not AutoPlugin yet https://github.com/sbt/sbt-testng/issues/16

Please see README#Usage <https://github.com/sbt/sbt-testng/tree/21db963e084313b5431012fdb779e49c08bdabc2#usage>
